### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by rinrinx** [neth1841/Torrent-Leech-Bot#1]
Not work repo

**Comment by rinrinx** [comment]
2022-03-19T18:35:23.457572+00:00 app[worker.1]: 20-Mar-22 00:05:23 - DEBUG - Using selector: EpollSelector [selector_events.py:59]
2022-03-19T18:35:23.461866+00:00 app[worker.1]: Traceback (most recent call last):
2022-03-19T18:35:23.461867+00:00 app[worker.1]:   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2022-03-19T18:35:23.461867+00:00 app[worker.1]:     return _run_code(code, main_globals, None,
2022-03-19T18:35:23.461868+00:00 app[worker.1]:   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
2022-03-19T18:35:23.461869+00:00 app[worker.1]:     exec(code, run_globals)
2022-03-19T18:35:23.461870+00:00 app[worker.1]:   File "/app/TorrentNT/__main__.py", line 5, in <module>
2022-03-19T18:35:23.461870+00:00 app[worker.1]:     from tobrot import (
